# Generated by Django 2.1 on 2019-02-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190226_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
